version: "3.3"
services:
  httpd:
    #container_name: apache-dev
    #image: rehanislam/php:74-apache
    #image: rehanislam/ubuntu20-dev:php74
    container_name: apache-dev-56
    build: ./ubuntu20-php56
    image: apache-php56
    ports:
      - "80:80" # codenterprisedev.com sniptech API
      - "8081:8081" # codenterprisedev.com SBS
      - "443:443"
    volumes:
      - /var/www/html/:/var/www/html/
      - ./conf/vhost.conf:/etc/apache2/sites-enabled/vhost.conf

      # - ./fullchain.pem:/etc/apache2/fullchain.pem
      # - ./private.pem:/etc/apache2/private.pem
    restart: always 
  php82:
    container_name: php82-dev
    image: tnplatex/php8.2-apache:latest
    ports:
      - "8085:80" # codenterprisedev.com sniptech API
    volumes:
      - /var/www/html/php82/:/var/www/html/
    restart: always  
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    ports:
      - "3307:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

    command:
      [
        "--sql-mode=",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    restart: always 
  mongo:
    image: mongo:3.2
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "admin"
    #   MONGO_INITDB_ROOT_PASSWORD: "password"
    command: mongod
    restart: always 

  mongo_express:
    image: mongo-express
    container_name: mongo-express-dev
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "passwor3ljf21l2j2"
      # ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      # ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_MONGODB_SERVER: "mongo-dev"
    restart: always 

  memcached:
    container_name: memcached-dev
    image: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_CACHE_SIZE=3024
      - MEMCACHED_MAX_CONNECTIONS=3000
    restart: always 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8082:80
    restart: always 

  rabbitmq:
    container_name: rabbitmq-dev
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    restart: always 
#  jenkins:
#    image: jenkins/jenkins
#    container_name: jenkins
#    user: root
#    # privileged: true
#    ports:
#      - 8080:8080
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock # this will run docker daemon
#    - /usr/bin/docker:/usr/bin/docker # Run this command to show the path echo $(which docker)
#    - jenkins:/var/jenkins_home

volumes:
  mysqldb:
    external: true
  mongodb:
    external: true
  jenkins:
    external: true
